#!/bin/bash

port1=$1
port2=$2

if [ -z $port1 ]
then
    port1="8081"
    port2="8081"
elif [ -z $port2 ]
then
    port2=$port1
fi

cd ~/Library/Android/sdk/platform-tools
echo "./adb reverse tcp:$port1 tcp:$port2"
./adb reverse tcp:$port1 tcp:$port2

exit 0