#!/bin/bash

# Import selectConnectedAndroidDevice function
. ./android/selectDevice

echo "Current folder: $PWD"
echo
echo "Call adb device script"

selectConnectedAndroidDevice

echo
echo "Selected device: $SELECTED_ANDROID_DEVICE"
echo "Current folder: $PWD"