#!/bin/bash

# Import selectConnectedAndroidDevice function
. ./android/selectConnectedAndroidDevice

echo "Call adb device script"

selectConnectedAndroidDevice SELECTED_ANDROID_DEVICE

echo
echo "Selected device: $SELECTED_ANDROID_DEVICE"