#!/bin/bash

# Path to root scripts directory
SCRIPT_PATH="${BASH_SOURCE[0]%/*}/$(readlink ${BASH_SOURCE[0]})"

# Remove "<dir>/../" from path | home/some/../foo -> home/foo
re='[^\/]+\/\.\.\/'
while [[ $SCRIPT_PATH =~ $re ]]; do
    SCRIPT_PATH="${SCRIPT_PATH/"${BASH_REMATCH[0]}"/}"
done

ROOT_DIR=${SCRIPT_PATH%/*}

SCRIPTS_DIR="$ROOT_DIR/scripts"

# Check platform specific or general script
case "$1" in
    "android")
        PLATFORM="android"
        SCRIPT_NAME=$2
    ;;
    "ios")
        PLATFORM="ios"
        SCRIPT_NAME=$2
    ;;
    *)
        PLATFORM=""
        SCRIPT_NAME=$1
    ;;
esac

# Variable with path of script for running
SCRIPT_PATH=$SCRIPTS_DIR/$PLATFORM/$SCRIPT_NAME/$SCRIPT_NAME

# Run script
$SCRIPT_PATH

# Check whether updates available for package
node $ROOT_DIR/utils/checkPackageUpdateAvailable.js

exit 0