#!/bin/bash

# Path to root scripts directory
ROOT_DIR=${BASH_SOURCE[0]%/*}

SCRIPTS_DIR="$ROOT_DIR/scripts"

# Check platform specific or general script
case "$1" in
    "android")
        PLATFORM="android"
        SCRIPT_NAME=$2
    ;;
    "ios")
        PLATFORM="ios"
        SCRIPT_NAME=$2
    ;;
    *)
        PLATFORM=""
        SCRIPT_NAME=$1
    ;;
esac

# Variable with path of script for running
SCRIPT_PATH=$SCRIPTS_DIR/$PLATFORM/$SCRIPT_NAME/$SCRIPT_NAME

echo ""
GREEN='\033[1;32m'
NO_COLOR='\033[0m'
echo -e "${GREEN}Run $SCRIPT_PATH${NO_COLOR}"
echo ""

# Run script
$SCRIPT_PATH

exit 0