#!/bin/bash

###
# Example:
# selectConnectedAndroidDevice VARIABLE_NAME
# Selected device ID ---> VARIABLE_NAME
###
function selectConnectedAndroidDevice {
    local RESULT_VAR=$1
    
    local PARENT_SCRIPT_DIR=$PWD
    # Go to adb folder
    cd ~/Library/Android/sdk/platform-tools
    
    # Get list of devices attached
    local DEVICES_CONNECTED=( $(
            ./adb devices | while read line
            do
                if [[ $line =~ .*device$ ]]; then
                    DEVICE_ID=$(echo $line | { read first _ ; echo $first ; } )
                    echo "$DEVICE_ID"
                fi
            done
        )
    )
    
    # Select device if need or can
    case "${#DEVICES_CONNECTED[@]}" in
        "0")
            echo "No devices attached"
            exit 0
        ;;
        "1")
            SELECTED_ANDROID_DEVICE=${DEVICES_CONNECTED[0]}
        ;;
        *)
            for i in ${!DEVICES_CONNECTED[@]}; do
                echo "$i: ${DEVICES_CONNECTED[$i]}"
            done
            echo
            read -p "Select one of devices attached by number (or first one will be used by default): " DEVICE_INDEX
            SELECTED_ANDROID_DEVICE=${DEVICES_CONNECTED[$DEVICE_INDEX]}
        ;;
    esac
    
    # Go back to parent script folder
    cd $PARENT_SCRIPT_DIR
    
    eval $RESULT_VAR="'$SELECTED_ANDROID_DEVICE'"
}