#!/bin/bash

# Import utils functions
. ../../.utils/android/selectConnectedAndroidDevice

# Go to adb folder
cd ~/Library/Android/sdk/platform-tools

# Select device if need or can
selectConnectedAndroidDevice DEVICE_ID

# Select port
echo
read -p "Enter port (or port=8081 will be used by default): " PORT_NUMBER
if [ -z $PORT_NUMBER ]
then
    PORT_NUMBER="8081"
fi

echo
echo "Run ./adb -s $DEVICE_ID reverse tcp:$PORT_NUMBER tcp:$PORT_NUMBER"
./adb -s $DEVICE_ID reverse tcp:$PORT_NUMBER tcp:$PORT_NUMBER

exit 0