#!/bin/bash

# Go to adb folder
cd ~/Library/Android/sdk/platform-tools

# Get list of devices attached
DEVICES_CONNECTED=( $(
        ./adb devices | while read line
        do
            if [[ $line =~ .*device$ ]]; then
                DEVICE_ID=$(echo $line | { read first _ ; echo $first ; } )
                echo "$DEVICE_ID"
            fi
        done
    )
)

# Select device if need or can
case "${#DEVICES_CONNECTED[@]}" in
    "0")
        echo "No devices attached"
        exit 0
    ;;
    "1")
        SELECTED_DEVICE=${DEVICES_CONNECTED[0]}
    ;;
    *)
        for i in ${!DEVICES_CONNECTED[@]}; do
            echo "$i: ${DEVICES_CONNECTED[$i]}"
        done
        echo
        read -p "Select one of devices attached by number (or first one will be used by default): " DEVICE_INDEX
        SELECTED_DEVICE=${DEVICES_CONNECTED[$DEVICE_INDEX]}
    ;;
esac

# Select port
echo
read -p "Enter port (or port=8081 will be used by default): " PORT_NUMBER
if [ -z $PORT_NUMBER ]
then
    PORT_NUMBER="8081"
fi

echo "Run ./adb -s $SELECTED_DEVICE reverse tcp:$PORT_NUMBER tcp:$PORT_NUMBER"
./adb -s $SELECTED_DEVICE reverse tcp:$PORT_NUMBER tcp:$PORT_NUMBER

exit 0