#!/usr/bin/env sh

cd ${BASH_SOURCE[0]%/*}
cd ..
echo $PWD

# Add rn-utils to PATH if need
if [[ ":$PATH:" == *":$PWD:"* ]]; then
    echo "PATH is OK"
else
    echo "Updating PATH in $HOME/.bash_profile"
    
    LINE_PATH="export PATH=\"\$PATH:$PWD\""
    COMPLETIONS_FILE_PATH="$PWD/completion/rn-utils"
    LINE_FOR_COMPLETION="[ -f $COMPLETIONS_FILE_PATH ] && . $COMPLETIONS_FILE_PATH"
    
    # Append line to ~/.bash_profile
    printf "\n$LINE_PATH\n$LINE_FOR_COMPLETION\n" >>$HOME/.bash_profile
    
    echo;
    RED='\033[1;31m'
    NO_COLOR='\033[0m'
    echo -e "${RED}Need to restart the Terminal!${NO_COLOR}"
    echo;
fi


exit 0